apiVersion: apps/v1
kind: Deployment
metadata:
  name: documents-service
  namespace: arkive
spec:
  replicas: 2
  selector:
    matchLabels:
      app: documents-service
  template:
    metadata:
      labels:
        app: documents-service
    spec:
      containers:
      - name: documents-service
        image: muohannedxd/documents-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: arkive-config
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: arkive-secrets
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: arkive-secrets
              key: POSTGRES_PASSWORD
        - name: STORAGE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: arkive-config
              key: STORAGE_SERVICE_URL
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /api/documents/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: documents-service
  namespace: arkive
spec:
  selector:
    app: documents-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP